<script setup lang="ts">
import { events, eventDate, meetupUrl } from '~/data/events'
useSeoMeta({ title: 'Encuentros y charlas — BilboDev', description: 'Charlas de programación y encuentros de la comunidad BilboDev en Bilbao. Consulta la próxima convocatoria y nuestro archivo de actividades.' })
const now = useState('site-now', () => Date.now())
onMounted(() => { now.value = Date.now() })
const selectedTopic = ref('Todos')
const topics = ['Todos', 'Multiplataforma', 'Desarrollo web', 'Diseño', 'Comunidad']
const upcoming = computed(() => events.filter(event => Date.parse(event.date) >= now.value).sort((a, b) => Date.parse(a.date) - Date.parse(b.date)))
const past = computed(() => events.filter(event => Date.parse(event.date) < now.value && (selectedTopic.value === 'Todos' || event.topic === selectedTopic.value)))
</script>
<template><div>
  <PageIntro number="02" label="ENCUENTROS" title="Menos pestañas abiertas. Más conversaciones." description="Nos reunimos en Bilbao para compartir programación, aprender de otras experiencias y poner cara a la comunidad. Las convocatorias y las inscripciones se publican en Meetup." />
  <section class="wrap agenda-upcoming"><div class="eyebrow accent">LO PRÓXIMO</div><article v-for="event in upcoming" :key="event.id" class="featured-event"><div class="featured-date"><strong>{{ eventDate(event.date, { day: '2-digit' }) }}</strong><span>{{ eventDate(event.date, { month: 'long', year: 'numeric' }) }}</span></div><div><span class="tag">{{ event.topic }}</span><h2>{{ event.title }}</h2><p>{{ event.description }}</p><div class="event-meta"><span>{{ event.location }}</span><span>{{ eventDate(event.date, { weekday: 'long', hour: '2-digit', minute: '2-digit' }) }} h</span></div><a class="button primary" :href="event.url" target="_blank" rel="noopener noreferrer">Ver convocatoria e inscribirme en Meetup ↗</a><p class="small muted">Consulta el aforo, las condiciones y posibles cambios en la convocatoria original.</p></div></article><div v-if="!upcoming.length" class="empty-events"><h2>Preparando la próxima conversación.</h2><p>La siguiente fecha se anunciará en nuestro grupo. Mientras tanto, puedes explorar los encuentros anteriores.</p><a :href="meetupUrl" class="text-link" target="_blank" rel="noopener noreferrer">Consultar novedades en Meetup ↗</a></div></section>
  <section class="wrap archive-section"><div class="section-heading"><div><div class="eyebrow">EL CONOCIMIENTO QUE YA COMPARTIMOS</div><h2>Archivo de encuentros.</h2></div><span class="small muted">Desde noviembre de 2025</span></div><div class="filter-bar" role="group" aria-label="Filtrar encuentros por temática"><button v-for="topic in topics" :key="topic" :aria-pressed="selectedTopic === topic" :class="{ selected: selectedTopic === topic }" @click="selectedTopic = topic">{{ topic }}</button></div><div aria-live="polite"><p class="results-count small muted">{{ past.length }} {{ past.length === 1 ? 'encuentro' : 'encuentros' }}</p><article v-for="event in past" :key="event.id" class="archive-event"><time :datetime="event.date">{{ eventDate(event.date, { day: '2-digit', month: 'short', year: 'numeric' }) }}</time><div><span class="eyebrow lavender">{{ event.topic }}</span><h3>{{ event.title }}</h3><p>{{ event.description }}</p><span class="small muted">{{ event.location }}</span></div><a :href="event.url" target="_blank" rel="noopener noreferrer" class="archive-link" :aria-label="`Consultar ${event.title} en el archivo de Meetup`">Meetup ↗</a></article><p v-if="!past.length" class="empty-events">Todavía no hay encuentros pasados de esta temática. Prueba con otra categoría.</p></div><p class="source-note">Agenda revisada el 10 de septiembre de 2026 a partir de las convocatorias de <a :href="meetupUrl" target="_blank" rel="noopener noreferrer">BilboDev en Meetup</a>.</p></section>
</div></template>
