<script setup lang="ts">
import { association } from '~/data/association'
useSeoMeta({ title: 'Transparencia — BilboDev', description: 'Nuestra misión, la actividad de BilboDev y la información institucional de la asociación.' })
</script>
<template><div><PageIntro number="04" label="TRANSPARENCIA" title="Una comunidad abierta. Una asociación que se explica." description="Saber quiénes somos, qué hacemos y cómo nos organizamos forma parte de construir confianza." />
<section class="wrap transparency-content"><DemoNotice v-if="association.demo" /><div class="editorial-grid inner"><div class="eyebrow">IDENTIDAD Y FINALIDAD</div><div class="prose"><h2>El conocimiento como fin común.</h2><p>La Asociación Tecnológica BilboDev tiene su sede en Bilbao y promueve el conocimiento y el desarrollo tecnológico enfocado en la programación multiplataforma dentro de Euskadi. Nace en noviembre de 2025 y desarrolla una actividad de encuentro y divulgación sin ánimo de lucro.</p><dl class="info-table"><div><dt>Denominación</dt><dd>{{ association.name }}</dd></div><div><dt>NIF · ejemplo</dt><dd>{{ association.nif }}</dd></div><div><dt>Registro · ejemplo</dt><dd>{{ association.registry }}</dd></div><div><dt>Domicilio · ejemplo</dt><dd>{{ association.address }}</dd></div><div><dt>Ámbito de actividad</dt><dd>Euskadi</dd></div></dl></div></div>
<div class="editorial-grid inner"><div class="eyebrow">GOBIERNO · EJEMPLO</div><div class="prose"><h2>Las personas detrás.</h2><p>Composición ilustrativa de la junta directiva. Los nombres y cargos deberán contrastarse con el acta vigente de la asociación.</p><dl class="info-table"><div v-for="member in association.board" :key="member.role"><dt>{{ member.role }}</dt><dd>{{ member.name }} <span class="small muted">(ficticio)</span></dd></div></dl></div></div>
<div class="editorial-grid inner"><div class="eyebrow">ACTIVIDAD Y ALCANCE</div><div class="prose"><h2>Lo que ya estamos compartiendo.</h2><p>Organizamos charlas con periodicidad mensual, anunciadas en Meetup. Los temas recorren el desarrollo web, las herramientas, el diseño y el trabajo entre plataformas.</p><p>Más de 200 personas forman parte del grupo de Meetup. Esta cifra describe la comunidad en esa plataforma; no es un recuento de personas socias ni de asistentes únicos a los encuentros.</p><NuxtLink class="text-link" to="/agenda">Consultar el archivo de actividades ↗</NuxtLink></div></div>
<div class="editorial-grid inner"><div class="eyebrow">DOCUMENTACIÓN</div><div class="prose"><h2>Información institucional.</h2><p>Esta versión todavía no incorpora estatutos, acta de constitución ni cuentas aprobadas. No se presentan cifras económicas ni documentos ficticios como si fueran oficiales.</p><p>Para solicitar información sobre la asociación o sobre la forma de participar, puedes contactar con la organización a través de sus canales públicos.</p><NuxtLink class="text-link" to="/contacto">Contactar con la asociación ↗</NuxtLink></div></div></section>
</div></template>
